version: '3.3'

services:
  django:
    build: backend
    command: uvicorn main.asgi:application --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    volumes:
      - ./backend/:/usr/src/backend/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"

  db:
    image: postgres:15.4-alpine3.18
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgres/data/

volumes:
  postgres_data:
