version: '3.3'

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: uvicorn main.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - static_volume:/home/backend/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"

  db:
    image: postgres:15.4-alpine3.18
    env_file:
      - ./.env.db.prod
    volumes:
      - postgres_data:/var/lib/postgres/data/


  nginx:
    build: nginx
    volumes:
      - static_volume:/home/backend/web/static
    ports:
      - "80:80"
    depends_on:
      - django



volumes:
  postgres_data:
  static_volume: